# Generated by Django 4.1.7 on 2025-06-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_product_cayegory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cayegory',
            new_name='category',
        ),
    ]
